export enum AUTH_ACTION_TYPES {
  CHECKING = 'CHECKING',
  AUTHENTICATED = 'AUTHENTICATED',
  SIGN_UP = 'SIGN_UP',
  ADD_ERROR = 'ADD_ERROR',
  REMOVE_ERROR = 'REMOVE_ERROR',
  NOT_AUTHENTICATED = 'NOT_AUTHENTICATED',
  LOGOUT = 'LOGOUT',
}
